function(spark_coverage_exemption target result)
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/coverage-exemptions.json" policy)
    string(JSON expected ERROR_VARIABLE absent GET "${policy}" targets "${target}")
    get_target_property(origin "${target}" SOURCE_DIR)
    get_target_property(options "${target}" LINK_OPTIONS)
    if(absent)
        cmake_path(IS_PREFIX PROJECT_SOURCE_DIR "${origin}" NORMALIZE project_owned)
        if(project_owned AND NOT origin MATCHES "/_deps/" AND options MATCHES "nostartfiles")
            message(FATAL_ERROR "Unreviewed no-startup coverage target: ${target}")
        endif()
        set(${result} FALSE PARENT_SCOPE)
        return()
    endif()

    get_target_property(kind "${target}" TYPE)
    get_target_property(imported "${target}" IMPORTED)
    string(JSON expected_origin GET "${expected}" source_dir)
    if(expected_origin STREQUAL ".")
        set(expected_origin "${PROJECT_SOURCE_DIR}")
    else()
        cmake_path(ABSOLUTE_PATH expected_origin BASE_DIRECTORY "${PROJECT_SOURCE_DIR}" NORMALIZE)
    endif()
    if(imported OR NOT kind STREQUAL "SHARED_LIBRARY" OR NOT origin STREQUAL expected_origin
            OR NOT "-nostartfiles" IN_LIST options)
        message(FATAL_ERROR "Coverage exemption target contract changed: ${target}")
    endif()

    get_target_property(sources "${target}" SOURCES)
    set(actual_sources "")
    foreach(source IN LISTS sources)
        if(source MATCHES "^\\$<")
            message(FATAL_ERROR "Unresolved coverage exemption source: ${target}")
        endif()
        cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${origin}" NORMALIZE)
        list(APPEND actual_sources "${source}")
    endforeach()
    string(JSON source_count LENGTH "${expected}" sources)
    math(EXPR last_source "${source_count} - 1")
    set(expected_sources "")
    foreach(index RANGE 0 ${last_source})
        string(JSON source GET "${expected}" sources ${index})
        cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${PROJECT_SOURCE_DIR}" NORMALIZE)
        list(APPEND expected_sources "${source}")
    endforeach()
    list(SORT actual_sources)
    list(SORT expected_sources)
    if(NOT actual_sources STREQUAL expected_sources)
        message(FATAL_ERROR "Coverage exemption sources changed: ${target}")
    endif()
    string(JSON definition ERROR_VARIABLE no_definition GET "${expected}" definition)
    if(NOT no_definition)
        get_target_property(definitions "${target}" COMPILE_DEFINITIONS)
        if(NOT definition IN_LIST definitions)
            message(FATAL_ERROR "Coverage exemption definition changed: ${target}")
        endif()
    endif()

    get_target_property(binary_dir "${target}" BINARY_DIR)
    set(entry "{}")
    foreach(field IN ITEMS target kind origin binary_dir)
        set(value "${${field}}")
        string(REPLACE "\\" "\\\\" value "${value}")
        string(REPLACE "\"" "\\\"" value "${value}")
        string(JSON entry SET "${entry}" "${field}" "\"${value}\"")
    endforeach()
    string(JSON entry SET "${entry}" type "\"${kind}\"")
    string(JSON entry REMOVE "${entry}" kind)
    string(JSON entry SET "${entry}" source_dir "\"${origin}\"")
    string(JSON entry REMOVE "${entry}" origin)
    string(JSON entry SET "${entry}" sources "[]")
    set(index 0)
    foreach(source IN LISTS actual_sources)
        string(REPLACE "\"" "\\\"" source "${source}")
        string(JSON entry SET "${entry}" sources ${index} "\"${source}\"")
        math(EXPR index "${index} + 1")
    endforeach()
    string(JSON entry SET "${entry}" reason "\"Source ELF contract forbids startup and finalization hooks\"")
    get_property(manifest GLOBAL PROPERTY SPARK_COVERAGE_EXEMPTIONS)
    string(JSON count LENGTH "${manifest}" exemptions)
    string(JSON manifest SET "${manifest}" exemptions ${count} "${entry}")
    set_property(GLOBAL PROPERTY SPARK_COVERAGE_EXEMPTIONS "${manifest}")
    set(${result} TRUE PARENT_SCOPE)
endfunction()
