include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/coverage_policy.cmake")

function(spark_coverage_collect directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        spark_coverage_exemption("${target}" exempt)
        if(exempt)
            continue()
        endif()
        get_target_property(imported "${target}" IMPORTED)
        get_target_property(kind "${target}" TYPE)
        if(imported OR NOT kind MATCHES "^(STATIC_LIBRARY|OBJECT_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|EXECUTABLE)$")
            continue()
        endif()
        get_target_property(origin "${target}" SOURCE_DIR)
        if(NOT origin STREQUAL PROJECT_SOURCE_DIR AND NOT origin MATCHES "^${PROJECT_SOURCE_DIR}/(src|tests)(/|$)")
            continue()
        endif()
        get_target_property(sources "${target}" SOURCES)
        set(owned FALSE)
        foreach(source IN LISTS sources)
            if(NOT source MATCHES "^\\$<")
                cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${origin}" NORMALIZE OUTPUT_VARIABLE absolute)
                if(absolute MATCHES "^${PROJECT_SOURCE_DIR}/(src|tests)/")
                    set(owned TRUE)
                endif()
            endif()
        endforeach()
        if(NOT owned)
            continue()
        endif()
        target_compile_options("${target}" PRIVATE --coverage -fprofile-update=atomic -O1 -g)
        if(kind MATCHES "^(SHARED_LIBRARY|MODULE_LIBRARY|EXECUTABLE)$")
            target_link_options("${target}" PRIVATE --coverage)
        endif()
        get_target_property(binary_dir "${target}" BINARY_DIR)
        file(APPEND "${PROJECT_BINARY_DIR}/coverage-targets.txt" "${target}\t${kind}\t${origin}\t${binary_dir}\n")
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        spark_coverage_collect("${child}")
    endforeach()
endfunction()

function(spark_coverage_finalize)
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "Coverage requires Linux Clang")
    endif()
    file(WRITE "${PROJECT_BINARY_DIR}/coverage-targets.txt" "")
    set_property(GLOBAL PROPERTY SPARK_COVERAGE_EXEMPTIONS "{\"policy_version\":1,\"exemptions\":[]}")
    spark_coverage_collect("${PROJECT_SOURCE_DIR}")
    get_property(manifest GLOBAL PROPERTY SPARK_COVERAGE_EXEMPTIONS)
    file(WRITE "${PROJECT_BINARY_DIR}/coverage-exemptions.json" "${manifest}\n")
endfunction()

cmake_language(DEFER DIRECTORY "${PROJECT_SOURCE_DIR}" CALL spark_coverage_finalize)
