include("${CMAKE_CURRENT_LIST_DIR}/coverage.cmake")

function(spark_diagnostic_optimization directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(options "${target}" COMPILE_OPTIONS)
        if("--coverage" IN_LIST options)
            target_compile_options("${target}" PRIVATE "${SPARK_DIAGNOSTIC_OPTIMIZATION}")
        endif()
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        spark_diagnostic_optimization("${child}")
    endforeach()
endfunction()

function(spark_diagnostic_finalize)
    if(NOT SPARK_DIAGNOSTIC_OPTIMIZATION MATCHES "^-O[012]$")
        message(FATAL_ERROR "Invalid ELF diagnostic optimization")
    endif()
    spark_diagnostic_optimization("${PROJECT_SOURCE_DIR}")
endfunction()

cmake_language(DEFER DIRECTORY "${PROJECT_SOURCE_DIR}" CALL spark_diagnostic_finalize)
